### ISSUE TITLE
Widgets plugin placeholder HTML not removed

### ISSUE THREAD

**Issue by JKirschbaumTG** [GrapesJS/ckeditor#20]
Hello,

Firstly thank you for all of the work you've done on GrapesJS and its affiliated projects. 

I'm having an issue with a plugin for CKEditor called Token Insertion ([https://ckeditor.com/cke4/addon/token](https://ckeditor.com/cke4/addon/token)). This plugin is dependent on (among other things) the widget plugin. From what I gather, the widget plugin adds a bunch of <span> tags that contain images for a drag handle to the HTML while working in the WYSIWYG. However, when you get the source of the editor, CKEditor seems smart enough to strip those span tags out. But when I get the HTML from GrapesJS, it still has these <span> tags in there with the drag handle images.   I'm getting the HTML from the storage manager's store function 

`store: function(data, success, error){
            storeGrapesJsTemplate(data["gjs-components"], data["gjs-css"], data["gjs-html"], data["gjs-styles"], success, error)
 }`

where storeGrapesJsTemplate stores off the pertinent information in the database.

Am I missing something? Is this a bug with the GrapesJS CKEditor plugin? It seems like maybe it's conflicting between the plugin needing to store these extra tags/markup in case the editor gets opened again, but also needing this markup not to show in the final product?

If I was using CKEditor alone I could obtain the desired markup just from 

`CKEDITOR.instances.myInstance.getData();`

Again, thank you for your time and for all the work put into this project!

**Comment by jcze91** [comment]
Hello,
Did you find some fix to this problem ? :)

**Comment by JKirschbaumTG** [comment]
> Hello,
> Did you find some fix to this problem ?
> Otherwise, I'd like also to have a response to its question. :)

I did not. I wound up writing a separate plugin for CKEditor myself that replaces text with tokens without adding any additional HTML to the WYSIWYG and is not dependent on the Widgets module. It functions, but doesn't highlight the tokens or make them immediately obvious within the editor.

**Comment by artf** [comment]
Closing this as `getData()` was integrated into plugin long time ago
