### ISSUE TITLE
Text Element Drag Issue.

### ISSUE THREAD

**Issue by YashPrince** [GrapesJS/ckeditor#23]
@artf I have used ckeditor plugins and it seems fine some level. There is small issue when we drag element in the canvas (Move element up or down level) then it recreate editor for same text element. So user can not know which editor they have use also it not looking good to show multiple editor for same element. So it will good that if user drag any elemmet then either new ckeditor should not create or delete previous one and add new.
I have checked it on you new project also and same issue happend on you site also.

![multipleckeditor](https://user-images.githubusercontent.com/40828744/46189828-49ce1080-c30e-11e8-8b9c-1be92bdf663e.png)
![multipleeditor](https://user-images.githubusercontent.com/40828744/46189829-4c306a80-c30e-11e8-8abb-a5bd26d49dcf.png)

**Comment by v8jupiter** [comment]
Have same issue with 0.15 rc build
