### ISSUE TITLE
Copy-Paste duplication // CKEDITOR

### ISSUE THREAD

**Issue by acamenhas** [GrapesJS/ckeditor#29]
Hi all,

I've integrated CKEDITOR as RTE on grapesjs.

But now, when i made a copy and paste the content shows duplicated.

Anyone had this bug before?

Thanks

**Comment by yucomds** [comment]
I've the same issue .. Do you figured out?

**Comment by yucomds** [comment]
Try this : 

```
    CKEDITOR.on('instanceReady', function (ev) {
        ev.editor.on('paste', function (ev) {
            ev.cancel();
        });
    });
```
