### ISSUE TITLE
Sync problems when focus is called

### ISSUE THREAD

**Issue by jcamejo** [GrapesJS/ckeditor#31]
Hi!

i am adapting the plugin, it's working great so far. The only issue i'm having is that when the ckeditor is invoked by any component that requires it, the cursor is not inserted inside the element that is going to be edited. 

My suspicion is that the focus action of the rte object is being fired before the instance is completely ready but i'm not 100% sure. The workaround for this issue was delaying the call of the focus action of the ckeditor object.

```
focus(el, rte) {
      // Do nothing if already focused
      if (rte && rte.focusManager.hasFocus) {
        return;
      }
      el.contentEditable = true;
      if(rte) {
	setTimeout(function() {
	rte.focus();
	}, 500);
      }
    }
```

This is a hackish  solution but i'm not sure how to deal with this situation, maybe there's a hook or listener where i can verify if the instance is ready to fire the focus action. I would gladly propose a pull request if there's something within the plugin range to fix this. It could be that this goes more into the Ckeditor territory.

Cheers!

**Comment by artf** [comment]
Should be fixed in the [latest release](https://github.com/GrapesJS/ckeditor/releases/tag/v1.0.1)
