### ISSUE TITLE
CKEditor FontColor Toolbar

### ISSUE THREAD

**Issue by dodyrosjidi** [GrapesJS/ckeditor#32]
Hi artf,

I have a problem with CKEditor Toolbar, how to show FontColor, FontSize at CKEditor toolbar?

**Comment by congweibai** [comment]
Hi there, 

I was doing add font and font size to CKEditor 4 in grapesjs. I intended to put font plugin CDN in my site and put 'font' in my CKEditor.config. Details could be found below.

I hope this could help you. Cheers

![Screen Shot 2020-12-14 at 1 07 49 pm](https://user-images.githubusercontent.com/53634020/102034210-5ff01a80-3e0d-11eb-8df0-838c09f91692.png)
![Screen Shot 2020-12-14 at 1 08 14 pm](https://user-images.githubusercontent.com/53634020/102034227-6e3e3680-3e0d-11eb-8f20-4a1d2b842771.png)
