### ISSUE TITLE
Link edit misbehaviour

### ISSUE THREAD

**Issue by RyanFlm** [GrapesJS/ckeditor#36]
Hello,
I've found a malfunction while editing links inside of text blocks.
The first time you toggle the CKEditor with double click on a text block, everything works fine, but for the second and following blocks you make a double click to open up the CKEditor the links aren't recognized correctly. You can edit those links. The Editor can't handle them correctly.
I've searched for an error log but found nothing.

This issue also appears in this [demo](https://grapesjs.com/demo-newsletter-editor.html).
I'll hope for some solution
Kind regards
Maxi

**Comment by insssomniac** [comment]
Hi, the problem still persists. Is there any solution?

**Comment by artf** [comment]
Closing as currently seems to be working
