### ISSUE TITLE
Some CKEditor features only usable if div element is edited

### ISSUE THREAD

**Issue by GiteKat** [GrapesJS/ckeditor#46]
Many CKEditor functions are only available, if the inline code is surrounded by an HTML div tag (see [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#property-blockless](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#property-blockless) and [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html)). 

This means that common CKEditor plugins (e.g. justify, list) can currently often not be used. 
Example: 
If I want to center a headline, then I do not get this option for an h-element. I tried wrapping it with a div, but this does not help.

What is the solution for e.g. centering an h-element?

**Comment by riodel27** [comment]
> 

Any update on this?
