### ISSUE TITLE
CK Editor toolbar does not move when text block height is changed

### ISSUE THREAD

**Issue by gustavohleal** [GrapesJS/ckeditor#48]
I added Ck Editor as the RTE, but when the height of a block grows the toolbar does not move with it. This only happens when the toolbar is bellow the block, as shown in the image above.

![image](https://user-images.githubusercontent.com/22385451/131171135-459429bb-ca5a-4d8b-8f44-a9386c98133f.png)

We have found a workaround for this using `editor.trigger('canvasScroll');` but had some issues to run it when a key is pressed as I explain in https://github.com/artf/grapesjs/issues/3731 on the main repo.

I also found an old issue that says this used to happen to the main RTE also. But it was fixed with him. How can I fix this with CK Editor? Is there a way that isn't a workaround?

**Comment by haseebahmad109** [comment]
@gustavohleal 

Hi, I am also facing this issue.
Were you able to find any fix for this issue? 

Any help will be greatly appreciated.

Thanks.

**Comment by ronaldohoch** [comment]
We solve it like this:

```js
    // Correção para o bug do ckeditor que fica por cima do texto
    editor.DomComponents.addType('text', {
        view: {
            events: {
                ...editor.DomComponents.getType('text').view.prototype.events,
                keyup: (e) => {
                    if (e.key == "Enter") {
                        // editor.trigger('canvasScroll');
                        editor.Canvas.getWindow().dispatchEvent(new CustomEvent('scroll'))
                    }
                }
            }
        },
    });
 ```

**Comment by artf** [comment]
Should be fixed in the [latest release](https://github.com/GrapesJS/ckeditor/releases/tag/v1.0.1)
