### ISSUE TITLE
Wrong position when open ckEditor.

### ISSUE THREAD

**Issue by ronaldohoch** [GrapesJS/ckeditor#52]
![image](https://user-images.githubusercontent.com/2287371/159703527-163d8062-dd0a-4210-80e7-f16adbaca43a.png)

I think the error is here.:
https://github.com/artf/grapesjs-plugin-ckeditor/blob/master/src/index.js#L89

This event didn't exist anymore, according to this PR: https://github.com/artf/grapesjs/pull/3953

**Comment by artf** [comment]
Should be fixed in the [latest release](https://github.com/GrapesJS/ckeditor/releases/tag/v1.0.1)
